apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-health-monitor
  description: FastAPI backend service exposing a health endpoint
  annotations:
    github.com/project-slug: Tanzeela-farooq/service-health-monitor
spec:
  type: service
  lifecycle: experimental
  owner: user:default/tanzeela-farooq
